runtime: inspired-arena-203606
api_version: 1
threadsafe: true

handlers:
- url: /
  script: FlaskDemo.app

- url: /aboutus\.html
  script: FlaskDemo.app

- url: /login\.html
  script: FlaskDemo.app

-url: /profile\.html
  script: FlaskDemo.app

- url: /.*
  script: FlaskDemo.app